### ISSUE TITLE
CSTV http broadcast freezes the program if Internet is disconnected or CSTV server shuts down

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#118]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

title says it

**Comment by saul** [comment]
What do you mean by "freeze the program"? If you mean `MoveNextAsync` never returns, then you can add a timeout to the cancellation token that it takes. If no tick is received over say, 15 secs, then you can try to restart the HttpBroadcastReader.

HttpBroadcastReader will keep trying to read where it left off. It's up to you to decide what should happen if the stream goes down.

**Comment by saul** [comment]
Resolved in v0.27.1
