### ISSUE TITLE
on PlayerHurt USP returns as P2000

### ISSUE THREAD

**Issue by aintalike217** [saul/demofile-net#18]
e.Weapon on PlayerHurt returns hpk2000 instead of usp_silencer. Also the same problem appears in player's Weapons, usp_silencer returned as hpk2000. It is strange since on PlayerDeath everything works right.

**Comment by saul** [comment]
For player_hurt, can you try getting the active weapon of the attacker instead? From that you should be able to get much more detail economy/item information than what's provided in the game event

**Comment by aintalike217** [comment]
Yes, it will be a fix for getting the right weapon on PlayerHurt. But if player active weapon is any from slot 1, and we want to get his full inventory USP-S still will be P2000 in MyWeapons. I understand that probably 99% don't bother about it, just decided to let you know.

**Comment by saul** [comment]
Please can you share some example code, a demo and what you expect the output to be? `ActiveWeapon` and `MyWeapons` should always give access to the weapon's economy info (e.g. whether it's USP-S, what the paintkit is, rarity, etc)
