### ISSUE TITLE
Parsing demofile throws 'Unrecognised serializer field: m_ePlayerFireEvent'

### ISSUE THREAD

**Issue by sgtfrankieboy** [saul/demofile-net#21]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

I'm trying to run the KillFeed sample with a demo from 2023-12-04 but it throws the error:

`'Unrecognised serializer field: m_ePlayerFireEvent'`

I've tried to run the SdkGen, but it also throws the same error.

### Affected demos

http://replay201.valve.net/730/003654429170693308593_1898149149.dem.bz2

**Comment by saul** [comment]
Fix should be available in v0.4.1, and we'll be more resilient to schema changes in future so they shouldn't require a new release of the library.
