### ISSUE TITLE
Usage from real-time application

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#22]
How would I use the library from real-time application which has it's own Message Loop (eg. GUI application) ?

Right now, the only way to parse demo file would be to call async method which would run in a different thread. It would be much better if the control of parsing is done by user of the library. That way, he can pause the parser, move to next tick, seek through history, etc.

Basically, a non-async version which allows the user to advance through demo file tick by tick.

I already implemented this myself (with additional API, no breaking changes), and would like to open PR, but I wanted to ask you what you think about it ?

**Comment by saul** [comment]
Here's a WIP PR - https://github.com/saul/demofile-net/pull/32. Are you still able to use async APIs? I've added `ConfigureAwait(false)` in all of the necessary places in the library, so you should be able to use them from WinForms now.

**Comment by in0finite** [comment]
Thank you for solving it so fast. 

That PR looks excellent. I think that's all I need. Async APIs are fine.

Btw, this is my environment: I am trying to use the library in Unity engine. However, Unity can't run anything newer than .NET 4.8. So, in order to use the library I can either:
- compile to native library (using AOT) then import it's methods and marshal data back-and-forth
- build the executable and run it from Unity, using Standard Input / Standard Output to marshal data - this is what I am currently doing
