### ISSUE TITLE
Pawn position is outside of buy-zone during freeze time

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#37]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

Sometimes, during freeze time pawn is placed outside of buy-zone.

To reproduce:

Go to: https://csunity-5172f.web.app/
Click Open -> Ok -> Select `navi-javelins-vs-9-pandas-fearless-m1-mirage.dem` -> Click Pause

Observe player "victoria" on the middle of screen. If you look around, you'll see his teammates are too far away from him. 

Once the round starts, his position will be correct.

His position coordinates are again 1024. You can see that in Inspector (but converted to meters, it will be 32).

### Affected demos

navi-javelins-vs-9-pandas-fearless-m1-mirage.dem

**Comment by in0finite** [comment]
```cs
var demo = new DemoParser();

await demo.StartReadingAsync(File.OpenRead("test.dem"), default);

while (demo.CurrentDemoTick.Value < 1305)
{
    await demo.MoveNextAsync(default);

    var player = demo.Players.SingleOrDefault(p => p.PlayerName == "victoria");
    if (player != null)
    {
        Console.WriteLine($"[{demo.CurrentDemoTick.Value}] Victoria position: {player.Pawn?.Origin}");
    }
}

Console.WriteLine("\nFinished!");
```

Until tick 1240, his position is { X = 1024, Y = -1024, Z = -1024 }.
This is when the round starts.
Then, until tick 1301, his Z coordinate stays at -1024.
And then, his position is correct.

**Comment by in0finite** [comment]
> Does this issue reproduce on other CS2 online demo viewers? I'm interested to know if this is an issue with this parser specifically, or with the data that is in the demo/how it was recorded.

> I'm also interested to know if you've seen this in any other demos, or just this one? It's possible that the issue has been fixed in the various demo recording/playback bugfixes that Valve have made over the past month or so.

I didn't test it with other online viewers.

I've seen this in many demos. And not just in the 1st round. It seems random.

Also, there is still a bug with pawn's position jittering. It just happens more rarely then before. I think it's connected to this bug.

**Comment by in0finite** [comment]
I just opened #45 . I suspect it's the same issue.

In the same demo, you can see pawns outside of buy-zones : pause & `demo_seek_tick 86464`. kyxsan is outside.

Another example: same match, but on Nuke. Beginning of 2nd round (1-0 score). zont1x is outside.

**Comment by in0finite** [comment]
After digging through code of both libraries for entire day, I finally nailed it.

Both libraries read the position from exact same location in bit buffer, but the difference is that `BitBuffer.ReadUBits(32)` will return 0 if bits available is 32, because `1 << 32` gives `1`, so the mask `((1 << numBits) - 1)` becomes 0.

Phiiuu  😓 

This means that everything that uses  `BitBuffer.ReadUBits(32)`, `BitBuffer.ReadFloat()`, `FieldDecode.DecodeFloatNoscale()`, is potentially broken and is subject to jittering from 0 to real value.

**Comment by saul** [comment]
Amazing work - many thanks for this! Great catch :)
