### ISSUE TITLE
Silenced weapons are not showing up

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#38]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

`CCSPlayerPawn.ActiveWeapon?.ServerClass?.Name` doesn't return silenced weapons (m4a1-s, usp-s), but returns their couterparts (m4a1, hkp2000).

**Comment by saul** [comment]
The server class is the name of the entity for these weapons. The entity is the same regardless of whether it's the silenced version or not. Can you instead try using:

```c#
CCSPlayerPawn.AttackerPawn?.ActiveWeapon?.AttributeManager.Item
```

This should give you the details you need
