### ISSUE TITLE
Pawn position still jittering

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#45]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

Pawn position is still jittering. Tested in one of latest demo files as of today (21 feb), and in older demos also.

To visualize:
- go to: https://csunity-5172f.web.app/
- open demo (Anubis map): https://www.hltv.org/matches/2369944/spirit-vs-heroic-pgl-cs2-major-copenhagen-2024-europe-rmr-b
- pause playback
- go to tick 2242 : open Console (press \` ) and type: `demo_seek_tick 2242`
- observe player Donk : for the next ~15 ticks, he is flying in air

**Comment by saul** [comment]
Fixed as part of #37
