### ISSUE TITLE
GOTV+ Broadcasting

### ISSUE THREAD

**Issue by BeepIsla** [saul/demofile-net#53]
Hey,

same feature request as the old S1 parser https://github.com/saul/demofile/issues/373

The broadcast URLs for the current major are https://cstv.challengermode.com/major/primary and https://cstv.challengermode.com/major/secondary

I assume its almost identical to the CSGO one, convars are all the same at least

**Comment by saul** [comment]
Hi, thanks for the suggestion.

WIP PR for this here: https://github.com/saul/demofile-net/pull/54

The protocol is different but it wasn't too hard to reverse engineer. I can't test it fully as I think the stream finished a couple of hours ago.

Give it a shot and let me know how you get on.

**Comment by BeepIsla** [comment]
Thanks for the most part it seems to work except I do not seem to receive any `Source1GameEvents` events, might be just due to how CSTV broadcasting works? I receive other events though such as `EntityEvents`, `GameEvents`, and `PacketEvents`. I am able to read the game state fine (Rounds played, team scores, players, etc)

**Comment by saul** [comment]
It's very possible that legacy Source 1 game events aren't available in CS2 broadcasts.

**Comment by LaihoE** [comment]
I tried parsing the broadcast myself and I'm seeing a bunch of GE_Source1LegacyGameEvent being fired :thinking: Maybe they fixed it?

**Comment by BeepIsla** [comment]
Seems like only some events don't fire, like RoundEnd. RoundOfficiallyEnded and PlayerDeath do work for example. Not sure which ones specifically work and don't work.

**Comment by in0finite** [comment]
@saul  When do you think you can finish this PR ? Is there anything left to be done ?

I would also like `StartReading()/MoveNext()` approach, but I could implement that myself in a separate PR.
