### ISSUE TITLE
Can I get player profile picture?

### ISSUE THREAD

**Issue by brago671** [saul/demofile-net#55]
I have a need in getting player pictures. Can i get those via DemoParser?
I can use Steam API and SteamID from parser but would be easier if they are already parsed.
----
I realy like the library. Great work

**Comment by saul** [comment]
You can get the players 64-bit Steam ID with `CCSPlayerController.PlayerInfo.Steamid`. Once you have that, you can pull the avatar URL with Steam's web APIs: https://developer.valvesoftware.com/wiki/Steam_Web_API#GetPlayerSummaries_.28v0002.29

Hope that helps
