### ISSUE TITLE
`RoundStartTicks` not available

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#73]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

`CDemoFileInfo.GameInfo?.Cs?.RoundStartTicks` property is not available in any demo.

`CDemoFileInfo.GameInfo` is always null.

### Code to reproduce

```csharp
var stream = new MemoryStream(File.ReadAllBytes(path));

var demo = new DemoParser();

demo.DemoEvents.DemoFileInfo += e =>
{
    Console.WriteLine($"DemoFileInfo:\n");

    var jsonSerializerOptions = new JsonSerializerOptions() { WriteIndented = true };
    string jsonStr = JsonSerializer.Serialize(e, jsonSerializerOptions);

    Console.WriteLine($"RoundStartTicks: {e.GameInfo?.Cs?.RoundStartTicks?.Count}\n");
    Console.WriteLine(jsonStr);

    Console.WriteLine($"\n");
};

await demo.ReadAllAsync(stream);
```

**Comment by saul** [comment]
Thanks for reporting. Is this data available in other parsers?

**Comment by in0finite** [comment]
I didn't check other parsers. I don't know if any parser actually reads `CDemoFileInfo`. I just assumed that data is there, to accelerate seeking through rounds.

**Comment by saul** [comment]
I'm going to assume that this data simply isn't in the demo files - please reopen if you can parse this data with another parser. Thanks
