### ISSUE TITLE
Support for POV demos

### ISSUE THREAD

**Issue by in0finite** [saul/demofile-net#85]
Currently, every POV demo crashes the parser.

**Comment by saul** [comment]
I have explored this in the past and I don't think it was too much work. I'm unlikely to have time to progress it in the near term so PRs are welcome as always

**Comment by saul** [comment]
Just to address the "I don't think you want contributions": To set expectations, I work on this project in my spare time, for free. I can't promise that every comment/question will be responded to, although I do try. Similarly I can't guarantee that PRs are merged quickly or at all. I run the project as a best effort. 

Back to the issue at hand - are you able to provide a decent length POV demo that I can test with?

**Comment by in0finite** [comment]
I have to say I am very disappointed. I've chosen this library because I'm good at .NET and thought I can improve it. The fact that you are ignoring comments and my attempts to improve the library tell me that you don't care about it. I don't even understand why you made it open source ?? 

You want to do everything yourself ? Fine. At least tell me "I don't want this feature" or "it's not a priority" or "I don't have time". Don't say "PRs are welcome as always" when I wait 6 months for it (even though it's already done and simply needs a click of a button).

>  are you able to provide a decent length POV demo that I can test with?

No, currently I can't provide any POV demos, when I obtain some that can be shared, I will let you know.
