### ISSUE TITLE
Example of multithreaded parsing

### ISSUE THREAD

**Issue by xGuysOG** [saul/demofile-net#99]
### Research

- [X] I've already searched and I could not find an existing issue or discussion about this issue.

### Description

Would be awesome to see some examples of it, since none was added when the new feature was created, just for new people as they find the libary.

### Code to reproduce

```csharp
none
```

### Affected demos

none

**Comment by saul** [comment]
Good idea, thanks for the suggestion. This is now available here: https://github.com/saul/demofile-net/tree/main/examples/DemoFile.Example.MultiThreaded
